require: rubocop-rails

AllCops:
  EnabledByDefault: true
  Exclude:
    - 'bin/**/*'
    - 'Rakefile'
  TargetRubyVersion: 2.6

Bundler/GemComment:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Style/ClassMethodsDefinitions:
  EnforcedStyle: self_class

Style/Copyright:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  AllowedCops:
    - Metrics/BlockLength
    - Metrics/ParameterLists

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  AllowParenthesesInCamelCaseMethod: true
  EnforcedStyle: omit_parentheses

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'

Style/WordArray:
  Enabled: true
  EnforcedStyle: percent
